-- AlterTable
ALTER TABLE "Part" ADD COLUMN "minQty" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Part" ADD COLUMN "maxQty" INTEGER;

-- AlterTable
ALTER TABLE "StockMove" ADD COLUMN "source" TEXT NOT NULL DEFAULT '';
ALTER TABLE "StockMove" ADD COLUMN "payment" TEXT NOT NULL DEFAULT 'PAID';
ALTER TABLE "StockMove" ADD COLUMN "billNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "StockMove" ADD COLUMN "paidAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Complaint" ADD COLUMN "laborCharge" DOUBLE PRECISION NOT NULL DEFAULT 1000;
ALTER TABLE "Complaint" ADD COLUMN "laborWork" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Complaint" ADD COLUMN "billNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Complaint" ADD COLUMN "billImage" BYTEA;
ALTER TABLE "Complaint" ADD COLUMN "billImageType" TEXT NOT NULL DEFAULT '';
